// File generated by FlutterFire CLI or custom setup.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv0wN59zSwse3DiJA3GyAp3p7Tt-paCug',
    appId: '1:102394890507:web:0deccc990ee206b7307a0e',
    messagingSenderId: '102394890507',
    projectId: 'savia-82257',
    authDomain: 'savia-82257.firebaseapp.com',
    storageBucket: 'savia-82257.firebasestorage.app',
    measurementId: 'G-EMM20HTSR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOej8QYAq2zmzZ3kIeBflRLVazgyn8b6Q',
    appId: '1:102394890507:android:c156e7e8c0da4a05307a0e',
    messagingSenderId: '102394890507',
    projectId: 'savia-82257',
    storageBucket: 'savia-82257.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAPsekZFBlvYvI5Gwtk85Nyb64pRYWUoE',
    appId: '1:102394890507:ios:15380f0f6bf895a1307a0e',
    messagingSenderId: '102394890507',
    projectId: 'savia-82257',
    storageBucket: 'savia-82257.firebasestorage.app',
    iosBundleId: 'com.invatech.kayo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAPsekZFBlvYvI5Gwtk85Nyb64pRYWUoE',
    appId: '1:102394890507:ios:15380f0f6bf895a1307a0e',
    messagingSenderId: '102394890507',
    projectId: 'savia-82257',
    storageBucket: 'savia-82257.firebasestorage.app',
    iosBundleId: 'com.invatech.kayo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv0wN59zSwse3DiJA3GyAp3p7Tt-paCug',
    appId: '1:102394890507:web:7a01181f26135775307a0e',
    messagingSenderId: '102394890507',
    projectId: 'savia-82257',
    authDomain: 'savia-82257.firebaseapp.com',
    storageBucket: 'savia-82257.firebasestorage.app',
    measurementId: 'G-BWPGMFX0ZL',
  );
}
